export type FarmerVideoType = "video" | "playlist"

export interface FarmerVideoCourse {
  id: string
  type: FarmerVideoType
  title: string
  directLink: string
  thumbnailUrl: string
  channel: string
  language: string
  whatItTeaches: string
  difficulty: "Beginner" | "Intermediate" | "Advanced"
  durationMinutes: number
  rating: number
  learners: number
  featured?: boolean
}

export const farmerVideoCatalog: FarmerVideoCourse[] = [
  {
    id: "fv-1",
    type: "video",
    title: "10 Profitable Crops to Grow in Karnataka",
    directLink: "https://www.youtube.com/watch?v=VHLZWhmNJ-U",
    thumbnailUrl: "https://img.youtube.com/vi/VHLZWhmNJ-U/hqdefault.jpg",
    channel: "Boss Wallah – Farming (ffreedom app / IndianMoney)",
    language: "English (India)",
    whatItTeaches: "Explains 10 high-profit crops suited to Karnataka and where they are mainly grown in the state.",
    difficulty: "Beginner",
    durationMinutes: 18,
    rating: 4.8,
    learners: 3247,
    featured: true,
  },
  {
    id: "fv-2",
    type: "video",
    title: "A beginner's guide to growing organic food",
    directLink: "https://www.youtube.com/watch?v=SOcxRMOjXWY",
    thumbnailUrl: "https://img.youtube.com/vi/SOcxRMOjXWY/hqdefault.jpg",
    channel: "Good Food Movement",
    language: "English",
    whatItTeaches: "How beginners should start organic farming with soil health, diversification, water, animals, and mindset.",
    difficulty: "Beginner",
    durationMinutes: 20,
    rating: 4.7,
    learners: 2890,
  },
  {
    id: "fv-3",
    type: "video",
    title: "Learn Organic Farming With Shankar – Ep 1 (Buying Land)",
    directLink: "https://www.youtube.com/watch?v=2F74xw1VK8E",
    thumbnailUrl: "https://img.youtube.com/vi/2F74xw1VK8E/hqdefault.jpg",
    channel: "Farmizen",
    language: "English",
    whatItTeaches: "How to choose farmland: climate, water, soil tests, pesticide drift risk, and market distance.",
    difficulty: "Intermediate",
    durationMinutes: 16,
    rating: 4.8,
    learners: 2310,
  },
  {
    id: "fv-4",
    type: "video",
    title: "Organic farming – Kannada",
    directLink: "https://www.youtube.com/watch?v=bRxrWg53bIQ",
    thumbnailUrl: "https://img.youtube.com/vi/bRxrWg53bIQ/hqdefault.jpg",
    channel: "ICAR Central Plantation Crops Research Institute (ICAR CPCRI)",
    language: "Kannada",
    whatItTeaches: "Organic coconut-based farming: residue recycling, vermicompost, coir pith composting, and basin management.",
    difficulty: "Intermediate",
    durationMinutes: 15,
    rating: 4.9,
    learners: 1980,
  },
  {
    id: "fv-5",
    type: "video",
    title: "2025 की Top 3 सब्ज़ी की खेती – लाखों की कमाई",
    directLink: "https://www.youtube.com/watch?v=pVuBKQnN2fM",
    thumbnailUrl: "https://img.youtube.com/vi/pVuBKQnN2fM/hqdefault.jpg",
    channel: "Indian Farmer",
    language: "Hindi",
    whatItTeaches: "Brinjal, okra, and tomato planning with spacing, varieties, pest management, and rough income logic.",
    difficulty: "Beginner",
    durationMinutes: 24,
    rating: 4.8,
    learners: 4210,
    featured: true,
  },
  {
    id: "fv-6",
    type: "video",
    title: "कौनसी फसलें देंगी 2026 में सबसे बड़ा PROFIT?",
    directLink: "https://www.youtube.com/watch?v=gneycmmHfq8",
    thumbnailUrl: "https://img.youtube.com/vi/gneycmmHfq8/hqdefault.jpg",
    channel: "Indian Farmer",
    language: "Hindi",
    whatItTeaches: "Cash crop options with investment, risk, yield, and per-acre profit logic.",
    difficulty: "Advanced",
    durationMinutes: 22,
    rating: 4.9,
    learners: 3900,
    featured: true,
  },
  {
    id: "fv-7",
    type: "video",
    title: "Modern Farming in Karnataka",
    directLink: "https://www.youtube.com/watch?v=cMFc2G4R6bs",
    thumbnailUrl: "https://img.youtube.com/vi/cMFc2G4R6bs/hqdefault.jpg",
    channel: "chandanavana",
    language: "Kannada",
    whatItTeaches: "A diversified Karnataka farm case study using natural and modern methods.",
    difficulty: "Intermediate",
    durationMinutes: 19,
    rating: 4.7,
    learners: 1725,
  },
  {
    id: "fv-8",
    type: "video",
    title: "5 High Profit Crops That Can Make You a Millionaire in India",
    directLink: "https://www.youtube.com/watch?v=o5KyTseJTrE",
    thumbnailUrl: "https://img.youtube.com/vi/o5KyTseJTrE/hqdefault.jpg",
    channel: "maximum cultivator",
    language: "English (Indian)",
    whatItTeaches: "Microgreens, saffron, bamboo, turmeric and exotic vegetables with investment, harvest time and earning logic.",
    difficulty: "Beginner",
    durationMinutes: 3,
    rating: 4.5,
    learners: 1600,
  },
  {
    id: "fv-9",
    type: "video",
    title: "Know about 10 most Profitable Crops to grow in India",
    directLink: "https://www.youtube.com/watch?v=HJmgfNHimP8",
    thumbnailUrl: "https://img.youtube.com/vi/HJmgfNHimP8/hqdefault.jpg",
    channel: "Boss Wallah – Farming (ffreedom app)",
    language: "English",
    whatItTeaches: "10 cash crops with climate fit, soil needs and profitability for small farmers.",
    difficulty: "Beginner",
    durationMinutes: 11,
    rating: 4.7,
    learners: 2100,
  },
  {
    id: "fv-10",
    type: "video",
    title: "ಬರಡನ್ನು ಬಂಗಾರ ಮಾಡಿದ ಇಂಜಿನಿಯರ್ | Organic Farming in Kannada",
    directLink: "https://www.youtube.com/watch?v=NmSQ1ktxUaU",
    thumbnailUrl: "https://img.youtube.com/vi/NmSQ1ktxUaU/hqdefault.jpg",
    channel: "chandanavana",
    language: "Kannada",
    whatItTeaches: "11-acre organic multi-layer farm case: soil building, crop mix, water-saving and certification journey.",
    difficulty: "Intermediate",
    durationMinutes: 20,
    rating: 4.8,
    learners: 1850,
  },
  {
    id: "fv-11",
    type: "video",
    title: "Best Organic Farming in Kannada (11 acre agriculture)",
    directLink: "https://www.youtube.com/watch?v=B1wnZPuUFCM",
    thumbnailUrl: "https://img.youtube.com/vi/B1wnZPuUFCM/hqdefault.jpg",
    channel: "chandanavana",
    language: "Kannada",
    whatItTeaches: "Jeevamrutha prep, drip + venturi setup, honey-bee integration, and zero-chemical operations.",
    difficulty: "Intermediate",
    durationMinutes: 22,
    rating: 4.8,
    learners: 1760,
  },
  {
    id: "fv-12",
    type: "video",
    title: "Sustainable Integrated Organic farming training in Kannada",
    directLink: "https://www.youtube.com/watch?v=Dl56EHfGeIw",
    thumbnailUrl: "https://img.youtube.com/vi/Dl56EHfGeIw/hqdefault.jpg",
    channel: "MICROBI AGROTECH PVT LTD",
    language: "Kannada",
    whatItTeaches: "Long-form masterclass on organic principles, soil health, rotations, inputs and practical methods.",
    difficulty: "Advanced",
    durationMinutes: 150,
    rating: 4.9,
    learners: 2400,
    featured: true,
  },
  {
    id: "fv-13",
    type: "video",
    title: "Digital Farmer | E-Nam (double profit explainer)",
    directLink: "https://www.youtube.com/watch?v=6lzXbHcboAc",
    thumbnailUrl: "https://img.youtube.com/vi/6lzXbHcboAc/hqdefault.jpg",
    channel: "Gaon Junction",
    language: "Hindi",
    whatItTeaches: "Quick explainer of e-NAM, One Nation One Market value, and farmer-side pricing benefits.",
    difficulty: "Beginner",
    durationMinutes: 3,
    rating: 4.6,
    learners: 1550,
  },
  {
    id: "fv-14",
    type: "video",
    title: "Farmer Registration | ENAM | FPO",
    directLink: "https://www.youtube.com/watch?v=Q4lb0s9iHik",
    thumbnailUrl: "https://img.youtube.com/vi/Q4lb0s9iHik/hqdefault.jpg",
    channel: "SFAC India (official)",
    language: "Hindi",
    whatItTeaches: "Official step-by-step farmer registration flow on e-NAM portal.",
    difficulty: "Beginner",
    durationMinutes: 12,
    rating: 4.7,
    learners: 1680,
  },
  {
    id: "fv-15",
    type: "video",
    title: "eNAM farmer registration and benefits",
    directLink: "https://www.youtube.com/watch?v=IuvRVlmjsUQ",
    thumbnailUrl: "https://img.youtube.com/vi/IuvRVlmjsUQ/hqdefault.jpg",
    channel: "कृषि खबर",
    language: "Hindi",
    whatItTeaches: "Full e-NAM training: benefits, registration, gate entry, lot creation, bidding and payment flow.",
    difficulty: "Intermediate",
    durationMinutes: 24,
    rating: 4.7,
    learners: 1920,
  },
]
